/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.headhunter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Vacancy service. Represents a row in the &quot;HH_Vacancy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.headhunter.model.impl.VacancyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.headhunter.model.impl.VacancyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vacancy
 * @generated
 */
@ProviderType
public interface VacancyModel extends BaseModel<Vacancy> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vacancy model instance should use the {@link Vacancy} interface instead.
	 */

	/**
	 * Returns the primary key of this vacancy.
	 *
	 * @return the primary key of this vacancy
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vacancy.
	 *
	 * @param primaryKey the primary key of this vacancy
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this vacancy.
	 *
	 * @return the uuid of this vacancy
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this vacancy.
	 *
	 * @param uuid the uuid of this vacancy
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the vacancy ID of this vacancy.
	 *
	 * @return the vacancy ID of this vacancy
	 */
	public long getVacancyId();

	/**
	 * Sets the vacancy ID of this vacancy.
	 *
	 * @param vacancyId the vacancy ID of this vacancy
	 */
	public void setVacancyId(long vacancyId);

	/**
	 * Returns the vacancy name of this vacancy.
	 *
	 * @return the vacancy name of this vacancy
	 */
	@AutoEscape
	public String getVacancyName();

	/**
	 * Sets the vacancy name of this vacancy.
	 *
	 * @param vacancyName the vacancy name of this vacancy
	 */
	public void setVacancyName(String vacancyName);

	/**
	 * Returns the employer name of this vacancy.
	 *
	 * @return the employer name of this vacancy
	 */
	@AutoEscape
	public String getEmployerName();

	/**
	 * Sets the employer name of this vacancy.
	 *
	 * @param employerName the employer name of this vacancy
	 */
	public void setEmployerName(String employerName);

	/**
	 * Returns the created at of this vacancy.
	 *
	 * @return the created at of this vacancy
	 */
	@AutoEscape
	public String getCreatedAt();

	/**
	 * Sets the created at of this vacancy.
	 *
	 * @param createdAt the created at of this vacancy
	 */
	public void setCreatedAt(String createdAt);

	/**
	 * Returns the salary from of this vacancy.
	 *
	 * @return the salary from of this vacancy
	 */
	public int getSalaryFrom();

	/**
	 * Sets the salary from of this vacancy.
	 *
	 * @param salaryFrom the salary from of this vacancy
	 */
	public void setSalaryFrom(int salaryFrom);

	/**
	 * Returns the salary to of this vacancy.
	 *
	 * @return the salary to of this vacancy
	 */
	public int getSalaryTo();

	/**
	 * Sets the salary to of this vacancy.
	 *
	 * @param salaryTo the salary to of this vacancy
	 */
	public void setSalaryTo(int salaryTo);

	/**
	 * Returns the salary gross of this vacancy.
	 *
	 * @return the salary gross of this vacancy
	 */
	public boolean getSalaryGross();

	/**
	 * Returns <code>true</code> if this vacancy is salary gross.
	 *
	 * @return <code>true</code> if this vacancy is salary gross; <code>false</code> otherwise
	 */
	public boolean isSalaryGross();

	/**
	 * Sets whether this vacancy is salary gross.
	 *
	 * @param salaryGross the salary gross of this vacancy
	 */
	public void setSalaryGross(boolean salaryGross);

	/**
	 * Returns the salary currency of this vacancy.
	 *
	 * @return the salary currency of this vacancy
	 */
	@AutoEscape
	public String getSalaryCurrency();

	/**
	 * Sets the salary currency of this vacancy.
	 *
	 * @param salaryCurrency the salary currency of this vacancy
	 */
	public void setSalaryCurrency(String salaryCurrency);

}